#! /bin/bash

API_HOST=""
STATUS=0

function invalid_arguments {
  echo "missing command(s) start | stop | test | only_test | restart | build | rebuild"
  echo "you may combine any commands in the order you wish to execute them"
  echo " "
  echo " start     :: start the docker containers"
  echo " stop      :: stop the docker containers"
  echo " test      :: build, start, test and stop docker containers"
  echo " only_test :: executes the test, docker containers must be running"
  echo " restart   :: restarts the docker containers"
  echo " build     :: will build the docker images to be used"
  echo " rebuild   :: see --> build"
  echo " "
  echo "Example:"
  echo "./eiffel-gerrit-plugin-script test"
  echo "      --> Will compile the source code to an executable jar and "
  echo "          Build the docker file and start the docker-compose"
  echo "          Execute the tests and then stop the running services"

  exit;
}

function do_stop {
  echo "########################################"
  echo "###### STOPPING DOCKER SERVICES ########"
  echo "########################################"

  source target/env.bash
  docker-compose -f target/docker-compose.yml down
  if [ $? -eq 1 ]; then
    echo "Failed to stop docker containers!"
    exit 1
  fi
}

function do_rebuild {
  echo "########################################"
  echo "######### BUILDING JARS ################"
  echo "########################################"

  mvn clean install package -DskipTests

  cp src/main/docker/env.bash target/env.bash
  cp src/main/docker/docker-compose.yml target/docker-compose.yml
  cp src/main/docker/Dockerfile target/Dockerfile

  JAR_LOCATION=$(ls target/ | grep '^eiffel-gerrit-plugin-[0-9]*.[0-9]*.[0-9]*.jar')
  docker build -f target/Dockerfile -t plugin-test target/ --build-arg JAR_LOCATION=./$JAR_LOCATION
  if [ $? -eq 1 ]; then
    echo "Failed to build docker file!"
    exit 1
  fi
}

function do_start {
  echo "########################################"
  echo "###### STARTING DOCKER SERVICES ########"
  echo "########################################"

  source target/env.bash
  docker-compose -f target/docker-compose.yml up -d

  wait_for_service "RABBITMQ" "target_rabbitmq" "15672"
  wait_for_service "GERRIT" "target_gerrit" "8080"
  wait_for_service "REMREM_PUBLISH" "target_publish" "8080"
  wait_for_service "REMREM_GENERATE" "target_generate" "8080"
}

function do_test {
  echo "########################################"
  echo "########### RUNNING TESTS ##############"
  echo "########################################"

  set_api_host target_gerrit
  mvn verify -DskipUTs -Dgerrit.url=$API_HOST
  STATUS=$?
}

function get_logs {
  docker logs $(docker ps | grep plugin-test | awk '{print $1}')
}

function do_restart {
  do_stop
  do_start
}

function do_full_test {
  do_rebuild
  do_start
  do_test
  do_stop
}

function set_api_host {
  container_name="$1"

  unamestr=$(uname)
  if [[ "$unamestr" == "Linux" ]]; then
    CONTAINER_ID=$(docker ps | grep ${container_name} | awk '{print $1}')
    API_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
  elif [[ "$unamestr" == MINGW64_NT* ]]; then
    API_HOST=localhost
  else
    echo "Unsupported operating system, this script currently only works in Linux and Windows!"
    exit 1
  fi
}

function check_supported_systems {
  unamestr=`uname`
  if [[ "$unamestr" != "Linux" && "$unamestr" != MINGW64_NT* ]]; then
    echo "Unsupported operating system, this script currently only works in Linux and Windows!"
    exit 1
  fi
}

function wait_for_service {
  service_name="$1"
  container_name="$2"
  container_port="$3"

  attempt_counter=0
  max_attempts=60

  set_api_host $container_name
  BASE_URL=http://$API_HOST:${container_port}

  printf "WAITING FOR $service_name TO START WITH URL: "$BASE_URL
  echo " "
  until $(curl --output /dev/null --silent --head --fail $BASE_URL); do
      if [ ${attempt_counter} -eq ${max_attempts} ];then
        printf " \e[91m FAILURE! \e[39m"
        echo " "
        echo "$service_name failed to start!"
        do_stop
        exit 1
      fi

      printf '.'
      attempt_counter=$(($attempt_counter+1))
      sleep 2
  done

  printf " \e[32m SUCCESS! \e[39m"
  echo " "
}

if [ $# -eq 0 ]; then
  invalid_arguments
fi

check_supported_systems

if [[ "start stop test only_test restart rebuild build" =~ .*${1}.* ]];
then
  while [ "$1" != "" ]
  do
    echo "Executing command: '$1'"
    case "$1" in
            start)     do_start;;
            stop)      do_stop;;
            test)      do_full_test;;
            only_test) do_test;;
            restart)   do_restart;;
            rebuild)   do_rebuild;;
            build)     do_rebuild;;
    esac
    shift
  done
else
  invalid_arguments
  STATUS=1
fi

exit $STATUS
