version: '2'

services:
  gerrit:
    image: plugin-test:latest
    ports:
      - "5005:5005"
      - "8080:8080"
      - "29418:29418"
    networks:
      - host-net

  rabbitmq:
    restart: always
    image: ${RABBITMQ_IMAGE}
    expose:
      - "15672"
      - "5672"
    ports:
      - "${RABBITMQ_WEB_PORT}:15672"
      - "${RABBITMQ_AMQP_PORT}:5672"
    networks:
      host-net:
        aliases:
          - rabbitmq
    environment:
      - RABBITMQ_USERNAME=myuser
      - RABBITMQ_PASSWORD=myuser
      - RABBITMQ_VHOST=/

  generate:
    restart: always
    image: ${REMREM_GENERATE_IMAGE}
    expose:
      - "8080"
    ports:
      - "${REMREM_GENERATE_PORT}:8080"
    environment:
      - server.port=8080
      - jasypt.encryptor.password=
      - activedirectory.generate.enabled=false
      - activedirectory.ldapUrl=
      - activedirectory.managerPassword=
      - activedirectory.managerDn=
      - activedirectory.rootDn=
      - activedirectory.userSearchFilter=
      - logging.level.root=OFF
      - logging.level.org.springframework.web=DEBUG
      - logging.level.com.ericsson.eiffel.remrem.producer=DEBUG
    networks:
      host-net:
        aliases:
          - generate

  publish:
    restart: always
    image: ${REMREM_PUBLISH_IMAGE}
    expose:
      - "8080"
    ports:
      - "${REMREM_PUBLISH_PORT}:8080"
    depends_on:
      - rabbitmq
    environment:
      - server.port=8080
      - jasypt.encryptor.password=
      - generate.server.uri=http://generate:8080
      - generate.server.path=/
      - activedirectory.publish.enabled=false
      - activedirectory.ldapUrl=
      - activedirectory.managerPassword=
      - activedirectory.managerDn=
      - activedirectory.rootDn=
      - activedirectory.userSearchFilter=
      - logging.level.root=OFF
      - logging.level.org.springframework.web=DEBUG
      - logging.level.com.ericsson.eiffel.remrem.producer=DEBUG
      - WAIT_MB_HOSTS=rabbitmq:${RABBITMQ_WEB_PORT}
      - rabbitmq.instances.jsonlist=${REMREM_PUBLISH_RABBITMQ_INSTANCES_LIST}
    networks:
      host-net:
        aliases:
          - publish

networks:
  host-net:
    driver: bridge
