#!/bin/bash

export TMP_DOWNLOAD_DIR=${FIREFOX_BINARY_FOLDER}
export INTEGRATION_TEST_FIREFOX_VERSION=66.0.3

mkdir -p ${TMP_DOWNLOAD_DIR}/ && wget "https://ftp.mozilla.org/pub/firefox/releases/${INTEGRATION_TEST_FIREFOX_VERSION}/linux-x86_64/en-GB/firefox-${INTEGRATION_TEST_FIREFOX_VERSION}.tar.bz2" -nv -O ${TMP_DOWNLOAD_DIR}/firefox-${INTEGRATION_TEST_FIREFOX_VERSION}.tar.bz2


echo "Extracting file ..."
tar -xjf ${TMP_DOWNLOAD_DIR}/firefox-${INTEGRATION_TEST_FIREFOX_VERSION}.tar.bz2 -C ${TMP_DOWNLOAD_DIR}/

chmod +x -R ${TMP_DOWNLOAD_DIR}/
